# Generated by Django 4.0 on 2022-01-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('author', models.CharField(default='unknown', max_length=10)),
                ('lang', models.CharField(max_length=10)),
                ('body', models.TextField(default='this is our book body')),
            ],
            options={
                'ordering': ['id', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookm',
            constraint=models.UniqueConstraint(fields=('id', 'title'), name='unique'),
        ),
    ]
