# Generated by Django 4.0 on 2022-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0003_alter_bookm_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookm',
            name='author',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookm',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
