# Generated by Django 4.0 on 2022-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0008_bookm_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookm',
            name='rank',
            field=models.FloatField(default='0.0'),
        ),
    ]
