# Generated by Django 4.0 on 2022-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0012_alter_bookm_author_alter_bookm_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookm',
            name='cover',
            field=models.CharField(default='unknown', max_length=500),
        ),
    ]
