# Generated by Django 4.0 on 2022-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookm',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
