# Generated by Django 4.0 on 2022-01-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0004_alter_bookm_author_alter_bookm_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.JSONField()),
            ],
        ),
    ]
