# Generated by Django 4.0 on 2022-01-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0005_bookmindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmindex',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
