# Generated by Django 4.0 on 2022-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0006_alter_bookmindex_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaccardGraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookId', models.IntegerField(default='-1')),
                ('neighbors', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
