# Generated by Django 4.0 on 2022-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0009_alter_bookm_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaccardgraph',
            name='totalDistance',
            field=models.FloatField(default='0.0'),
        ),
    ]
