# Generated by Django 4.0.2 on 2022-02-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengin_backend', '0013_bookm_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaccardgraph',
            name='centrality',
            field=models.FloatField(default='0.0'),
        ),
    ]
